### PR TITLE
modplug decoder: multichannel + midi support

### PR DESCRIPTION
**Pull request by r-lyeh**
Hey there Dimitri,

Let me know if you are interested in this PR.

I've bundled the modplug library into libnyquist.

Modplug is a PD licensed solution to load multichannel music (mod, s3m, xm, it...)
It also can play MIDI files and a wide range of WAVs. 
MIDI files (and .abc files) require the sound patches located in [pat/ folder](pat/): these samples are either PD or GPL licensed.

Most if not all of the work came from @JariKomppa 's Soloud repo, so kudos to him :)

### CODE REVIEW

**Comment by r-lyeh** [comment]
Btw, you'd need to update the project files like we did last time

**Comment by r-lyeh** [comment]
ping @ddiakopoulos :)

**Comment by ddiakopoulos** [comment]
So I want to merge this but that folder of binary patterns is killer: both 11mb and with some of that content GPL? Ack!

**Comment by r-lyeh** [comment]
lol
It's an optional folder after all.
I can remove the folder, but users will have to figure out how to recreate the soundpatches to play the MIDI songs.

**Comment by r-lyeh** [comment]
@toread https://musescore.org/en/handbook/soundfont

**Comment by r-lyeh** [comment]
ok, ready :D

**Comment by ddiakopoulos** [comment]
:+1: will merge this weekend

**Comment by r-lyeh** [comment]
woohoo :+1:

**Comment by r-lyeh** [comment]
Hey Dimitri,

I've added some more info on midi exporting and soundfont conversion (btw, regarding to the GPL timidity alternatives, the Fluid M3 is a good (and unique fully MIT licensed) soundfont, but it gets close to the gigabyte once converted to `.pat`, so it's better to have it apart from the repo :D)

Hope everything gets clearer from now

**Comment by ddiakopoulos** [comment]
Sorry this took so long :sweat_smile:

**Comment by r-lyeh** [comment]
xD

**Pull request merged**
