### PR TITLE
Make magic_map a global constant to avoid creating temporary instances on every call

### LINKED ISSUE #65: NyquistIO::Load creates temporary map every time it's called
The function `NyquistIO::Load(AudioData * data, const std::vector<uint8_t> & buffer)` creates a temporary map of magic identifiers to extensions every time it's called. Since this is a read-only map it's probably best to make this a global constant to eliminate the overhead.

The function also continues scanning for magic after it's found a match, is that required? Otherwise i'll make a separate issue for that.

### PR DESCRIPTION
**Pull request by SamVanheer**
Fixes #65

### CODE REVIEW

**Review by meshula — COMMENTED** [review]
The assumption here was that making magic_map const would cause it to be statically created and referenced, rather than created on every call to Load(). Is that not the case? Would it then be simplest to just add `static` to magic_map to accomplish it?

**Comment by SamVanheer** [comment]
Are there any changes that need to be made or is this fine?

**Comment by meshula** [comment]
The change looks good to me. Thanks for the answer to my question, I see why you structured it that way.

**Comment by ddiakopoulos** [comment]
@SamVanheer Could you resolve the conflict -- then I'll be happy to merge!

**Comment by SamVanheer** [comment]
@ddiakopoulos Should be good now.

**Pull request merged**
